@echo off
echo Starting Medusa Backend...
cd backend
echo Installing dependencies...
pnpm install
echo Initializing database...
pnpm run ib
echo Starting development server...
pnpm run dev
pause
